language: c

compiler:
  - gcc

before_install:
  - sudo apt-get install -y flex bison
  - sudo apt-get install -y binutils-mingw-w64-i686
  - sudo apt-get install -y gcc-mingw-w64-i686 gcc-mingw-w64-x86-64
  - sudo apt-get install -y mingw-w64 gcc-mingw-w64 texi2html

script:
  - export CC=i686-w64-mingw32-gcc
  - export CXX=i686-w64-mingw32-g++
  - mkdir build
  - cd build
  - ../configure --build=i686-linux-gnu --host=i686-w64-mingw32 --enable-targets=all --with-sysroot --disable-nls --disable-werror
  - make
  - cat config.log
